# Data loading

Experimenting with methods for loading data 

In [1]:
import sys
sys.path.append('../src/')


In [2]:
from Tokenizer import NLPTokenizer

In [3]:
a = NLPTokenizer("../data/tokenizer/tokens.json", 10)

In [4]:
a.encode("hello there, my name is ivan, this world is a complex place, haha, random sentence go brrrr, stupidly random sequence")

array([[28513,  1329,     9,  1551,  1948,   476, 20432,   413,     9,
          778],
       [  882,   476,    59,  7189,  1928,     9,   537,  1022,     9,
        14850],
       [ 7015,   563,   990,   231,   231,   231,     9, 17302,   461,
        14850],
       [   -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
        18124]])

## Experimenting with preparing data input

In [5]:
import numpy as np

In [6]:
randomSentence = "What do you even mean?."

In [7]:
def trainEncode(text:str, size:int=10):
    encodedMatrix = a.encode(text, False)
    x = []
    y = []
    for vector in encodedMatrix:
        for i in range(1, len(vector)):
            start = max(0, i-size)
            data = vector[start:i]
            if len(data) < size:
                data = np.pad(data, (size-len(data), 0), 'constant', constant_values=-1)
            x.append(data)
            y.append(vector[i])
    
    return np.vstack(x).astype(np.int32), np.array(y, dtype=np.int32)

In [8]:
x, y = trainEncode(randomSentence)

In [9]:
x.shape, y.shape

((6, 10), (6,))

In [10]:
import pandas as pd

In [48]:
df = pd.read_csv("../data/preprocessed/preprocessed.csv", chunksize=32, index_col=False)

In [56]:
type(df)

pandas.io.parsers.readers.TextFileReader

In [65]:
data = df.__next__()['0']

In [85]:
x, y = zip(*data.apply(lambda x: trainEncode(x, 80)))

In [88]:
np.vstack(x)

array([[   -1,    -1,    -1, ...,    -1,    -1,   456],
       [   -1,    -1,    -1, ...,    -1,   456, 14794],
       [   -1,    -1,    -1, ...,   456, 14794,   431],
       ...,
       [   -1,    -1,    -1, ...,   429,    24,   441],
       [   -1,    -1,    -1, ...,    24,   441,    59],
       [   -1,    -1,    -1, ...,   441,    59,   927]])

In [89]:
np.hstack(y)

array([14794,   431,  3818, ...,    59,   927,    11])