# Experiments with models

In [1]:
from ModelBuilds import createModel

In [2]:
from DataLoader import TrainLoader

In [3]:
import pandas as pd

In [12]:
import tensorflow as tf

# Reading data

In [4]:
a = pd.read_csv("../data/preprocessed/preprocessed.csv", chunksize=32, index_col=False)

In [5]:
trainLoader = TrainLoader(1300, 20, "../data/tokenizer/tokens.json", a)
data = trainLoader.getTensorflowDataset()

# Defining Models

In [6]:
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout

In [7]:
hiddenLayer1 = Sequential(
    [LSTM(300),
    Dropout(0.6)]
)

In [8]:
vocabSize = trainLoader.tokenizer.tokenizer.get_vocab_size()

In [9]:
model = createModel(trainLoader.sequenceLength, vocabSize, 400, hiddenLayer1, "lstm")

In [10]:
model.compile("adam", "categorical_crossentropy", ["accuracy"])

In [13]:
history = model.fit(data, epochs=100)

Epoch 1/100


TypeError: in user code:

    File "d:\projects\NLP Experiments\venv\lib\site-packages\keras\src\engine\training.py", line 1377, in train_function  *
        return step_function(self, iterator)
    File "d:\projects\NLP Experiments\venv\lib\site-packages\keras\src\engine\training.py", line 1360, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "d:\projects\NLP Experiments\venv\lib\site-packages\keras\src\engine\training.py", line 1349, in run_step  **
        outputs = model.train_step(data)
    File "d:\projects\NLP Experiments\venv\lib\site-packages\keras\src\engine\training.py", line 1127, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "d:\projects\NLP Experiments\venv\lib\site-packages\keras\src\engine\training.py", line 1185, in compute_loss
        return self.compiled_loss(
    File "d:\projects\NLP Experiments\venv\lib\site-packages\keras\src\engine\compile_utils.py", line 277, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "d:\projects\NLP Experiments\venv\lib\site-packages\keras\src\losses.py", line 143, in __call__
        losses = call_fn(y_true, y_pred)
    File "d:\projects\NLP Experiments\venv\lib\site-packages\keras\src\losses.py", line 270, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "d:\projects\NLP Experiments\venv\lib\site-packages\keras\src\losses.py", line 2221, in categorical_crossentropy
        return backend.categorical_crossentropy(
    File "d:\projects\NLP Experiments\venv\lib\site-packages\keras\src\backend.py", line 5573, in categorical_crossentropy
        target = tf.convert_to_tensor(target)

    TypeError: Failed to convert elements of SparseTensor(indices=Tensor("DeserializeSparse:0", shape=(None, 2), dtype=int64), values=Tensor("categorical_crossentropy/Cast:0", shape=(None,), dtype=float32), dense_shape=Tensor("shape:0", shape=(2,), dtype=int64)) to Tensor. Consider casting elements to a supported type. See https://www.tensorflow.org/api_docs/python/tf/dtypes for supported TF dtypes.


Problem: tensorflow doesn't support SparseTensor for training

In [14]:
# Example data preprocessing for SparseTensor
values = [1.0, 2.0, 3.0]
indices = [[0, 0], [1, 2], [2, 1]]
dense_shape = [3, 3]

sparse_tensor = tf.SparseTensor(indices=indices, values=values, dense_shape=dense_shape)


In [15]:
# Example model using Keras
testModel = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=4, output_dim=8),  # Example layer that accepts SparseTensor
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [22]:
tf.one_hot([3, 2, 3, 3], 100, dtype=tf.uint8)

<tf.Tensor: shape=(4, 100), dtype=uint8, numpy=
array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0